services:
  postgres: 
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432/tcp"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: on-failure
  # command: psql "host=localhost port=5432 user=postgres password=postgres sslmode=prefer"

  Mgtt.ECom.Web:
    image: ecommerce-service-be:0.1.0
    build:
      context: .
      dockerfile: backend/Mgtt.ECom/src/Mgtt.ECom.Web/Dockerfile
    env_file:
      - Mgtt.ECom.Web.env
    ports:
      - "5000:8080/tcp"

  # # Frontend with mocked data
  # e-commerce-service-mocked:
  #   image: ecommerce-service-fe:0.1.0
  #   build:
  #     context: .
  #     dockerfile: frontend/e-commerce-service-mocked/Dockerfile
  #   ports:
  #     - "4200:80/tcp"

volumes:
  postgres-db: