services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localhost:4566
      - AWS_PAGER=""
    volumes:
      - localstack-data:/data
    # Check: aws configure list

  postgres: 
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432/tcp"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - custom-network 
  # command: psql "host=localhost port=5432 user=postgres password=postgres sslmode=prefer"

volumes:
  postgres-db:
  localstack-data:

networks:
  custom-network: