erDiagram
    %% Bounded Contexts: User Management, Product Management, Order Management, Shopping Cart, Review Management
    
    %% Product Management Context
    Product {
        int ProductID
        string Name
        string Description
        float Price
        int Stock
        string[] Categoryies
        string ImageUrl
    }
    
    %% Order Management Context
    Order {
        int OrderID
        int UserID
        date OrderDate
        float TotalAmount
        string OrderStatus
    }
    
    OrderItem {
        int OrderItemID
        int OrderID
        int ProductID
        int Quantity
        float Price
    }
    
    %% Shopping Cart Context
    Cart {
        int CartID
        int UserID
        float TotalAmount
    }
    
    CartItem {
        int CartItemID
        int CartIDh
        int ProductID
        int Quantity
        float Price
    }
    
    %% Review Management Context
    Review {
        int ReviewID
        int ProductID
        int UserID
        int Rating
        string Comment
        date ReviewDate
    }

    %% Relationships
    Order ||--|{ OrderItem : contains
    Product ||--o{ OrderItem : includes
    Product ||--o{ Review : has
    Cart ||--|{ CartItem : contains
    Product ||--o{ CartItem : includes
