services:
  postgres: 
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432/tcp"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: on-failure
  # command: psql "host=localhost port=5432 user=postgres password=postgres sslmode=prefer"

volumes:
  postgres-db: