name: Auto-formatting and linting

on:
  pull_request:
    branches: [main]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Auto-formatting C# files
      uses: MGTheTrain/public-github-actions/.github/actions/auto-formatting-for-csharp@main
      with:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
    # auto-format Typescript 
    
