name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test C#
        uses: MGTheTrain/public-github-actions/.github/actions/test-csharp-repository@main
        with:
          TEST_WORKING_DIRECTORY: ./backend/Mgtt.ECom/test

      - name: Test TypeScript
        uses: MGTheTrain/public-github-actions/.github/actions/test-ng-typescript-repository@main
        with:
          WORKING_DIRECTORY: ./frontend/e-commerce-service

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'csharp, javascript'

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis for C#
        uses: github/codeql-action/analyze@v3
        with:
          languages: 'csharp'
          additional-analysis-path: /home/runner/work/e-commerce-service/results/csharp.sarif

      - name: Perform CodeQL Analysis for JavaScript
        uses: github/codeql-action/analyze@v3
        with:
          languages: 'javascript'
          additional-analysis-path: /home/runner/work/e-commerce-service/results/javascript.sarif

      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            /home/runner/work/e-commerce-service/results/csharp.sarif
            /home/runner/work/e-commerce-service/results/javascript.sarif