name: Check Git diffs

on:
  pull_request:
    branches: [main]

jobs:
  check-diffs:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install dotnet-format
      shell: bash
      run: dotnet tool install -g dotnet-format
      
    - name: Install Angular CLI
      run: npm install -g @angular/cli
      
    - name: Auto-format C#
      run: |
        find . -type f -name '*.csproj' -execdir dotnet format {} \;

    - name: Auto-format ng TypeScript
      run: | 
        npm i
        ng lint --fix
      working-directory: ./frontend/e-commerce-service

    - name: Check diffs
      run: |
        status=$(git status --porcelain=v1)
        if [[ -n "$status" ]]; then
          git diff
          exit 1
        fi